version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  test-and-push-image:
    description: Run Unit Tests and push to ECR
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test ./API/MyCookin.UnitTests -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./API
          region: AWS_REGION
          repo: mycookin
          tag: "latest"
