//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyCookin.DAL.Statistics
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBStatisticsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBStatisticsEntities object using the connection string found in the 'DBStatisticsEntities' section of the application configuration file.
        /// </summary>
        public DBStatisticsEntities() : base("name=DBStatisticsEntities", "DBStatisticsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBStatisticsEntities object.
        /// </summary>
        public DBStatisticsEntities(string connectionString) : base(connectionString, "DBStatisticsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBStatisticsEntities object.
        /// </summary>
        public DBStatisticsEntities(EntityConnection connection) : base(connection, "DBStatisticsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsersActionsStatistics> UsersActionsStatistics
        {
            get
            {
                if ((_UsersActionsStatistics == null))
                {
                    _UsersActionsStatistics = base.CreateObjectSet<UsersActionsStatistics>("UsersActionsStatistics");
                }
                return _UsersActionsStatistics;
            }
        }
        private ObjectSet<UsersActionsStatistics> _UsersActionsStatistics;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsersActionsStatistics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsersActionsStatistics(UsersActionsStatistics usersActionsStatistics)
        {
            base.AddObject("UsersActionsStatistics", usersActionsStatistics);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDUser">No Metadata Documentation available.</param>
        /// <param name="iDRelatedObject">No Metadata Documentation available.</param>
        /// <param name="actionType">No Metadata Documentation available.</param>
        /// <param name="comments">No Metadata Documentation available.</param>
        /// <param name="dateAction">No Metadata Documentation available.</param>
        /// <param name="fileOrigin">No Metadata Documentation available.</param>
        /// <param name="searchString">No Metadata Documentation available.</param>
        /// <param name="otherInfo">No Metadata Documentation available.</param>
        public int USP_InsertUserActionStatistic(Nullable<global::System.Guid> iDUser, Nullable<global::System.Guid> iDRelatedObject, Nullable<global::System.Int32> actionType, global::System.String comments, Nullable<global::System.DateTime> dateAction, global::System.String fileOrigin, global::System.String searchString, global::System.String otherInfo)
        {
            ObjectParameter iDUserParameter;
            if (iDUser.HasValue)
            {
                iDUserParameter = new ObjectParameter("IDUser", iDUser);
            }
            else
            {
                iDUserParameter = new ObjectParameter("IDUser", typeof(global::System.Guid));
            }
    
            ObjectParameter iDRelatedObjectParameter;
            if (iDRelatedObject.HasValue)
            {
                iDRelatedObjectParameter = new ObjectParameter("IDRelatedObject", iDRelatedObject);
            }
            else
            {
                iDRelatedObjectParameter = new ObjectParameter("IDRelatedObject", typeof(global::System.Guid));
            }
    
            ObjectParameter actionTypeParameter;
            if (actionType.HasValue)
            {
                actionTypeParameter = new ObjectParameter("ActionType", actionType);
            }
            else
            {
                actionTypeParameter = new ObjectParameter("ActionType", typeof(global::System.Int32));
            }
    
            ObjectParameter commentsParameter;
            if (comments != null)
            {
                commentsParameter = new ObjectParameter("Comments", comments);
            }
            else
            {
                commentsParameter = new ObjectParameter("Comments", typeof(global::System.String));
            }
    
            ObjectParameter dateActionParameter;
            if (dateAction.HasValue)
            {
                dateActionParameter = new ObjectParameter("DateAction", dateAction);
            }
            else
            {
                dateActionParameter = new ObjectParameter("DateAction", typeof(global::System.DateTime));
            }
    
            ObjectParameter fileOriginParameter;
            if (fileOrigin != null)
            {
                fileOriginParameter = new ObjectParameter("FileOrigin", fileOrigin);
            }
            else
            {
                fileOriginParameter = new ObjectParameter("FileOrigin", typeof(global::System.String));
            }
    
            ObjectParameter searchStringParameter;
            if (searchString != null)
            {
                searchStringParameter = new ObjectParameter("SearchString", searchString);
            }
            else
            {
                searchStringParameter = new ObjectParameter("SearchString", typeof(global::System.String));
            }
    
            ObjectParameter otherInfoParameter;
            if (otherInfo != null)
            {
                otherInfoParameter = new ObjectParameter("OtherInfo", otherInfo);
            }
            else
            {
                otherInfoParameter = new ObjectParameter("OtherInfo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("USP_InsertUserActionStatistic", iDUserParameter, iDRelatedObjectParameter, actionTypeParameter, commentsParameter, dateActionParameter, fileOriginParameter, searchStringParameter, otherInfoParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDRelatedObject">No Metadata Documentation available.</param>
        /// <param name="actionType">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> USP_CountByIDRelatedObjectAndActionType(Nullable<global::System.Guid> iDRelatedObject, Nullable<global::System.Int32> actionType)
        {
            ObjectParameter iDRelatedObjectParameter;
            if (iDRelatedObject.HasValue)
            {
                iDRelatedObjectParameter = new ObjectParameter("IDRelatedObject", iDRelatedObject);
            }
            else
            {
                iDRelatedObjectParameter = new ObjectParameter("IDRelatedObject", typeof(global::System.Guid));
            }
    
            ObjectParameter actionTypeParameter;
            if (actionType.HasValue)
            {
                actionTypeParameter = new ObjectParameter("ActionType", actionType);
            }
            else
            {
                actionTypeParameter = new ObjectParameter("ActionType", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("USP_CountByIDRelatedObjectAndActionType", iDRelatedObjectParameter, actionTypeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDUser">No Metadata Documentation available.</param>
        /// <param name="actionType">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> USP_CountByIDUserAndActionType(Nullable<global::System.Guid> iDUser, Nullable<global::System.Int32> actionType)
        {
            ObjectParameter iDUserParameter;
            if (iDUser.HasValue)
            {
                iDUserParameter = new ObjectParameter("IDUser", iDUser);
            }
            else
            {
                iDUserParameter = new ObjectParameter("IDUser", typeof(global::System.Guid));
            }
    
            ObjectParameter actionTypeParameter;
            if (actionType.HasValue)
            {
                actionTypeParameter = new ObjectParameter("ActionType", actionType);
            }
            else
            {
                actionTypeParameter = new ObjectParameter("ActionType", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("USP_CountByIDUserAndActionType", iDUserParameter, actionTypeParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBStatisticsModel", Name="UsersActionsStatistics")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsersActionsStatistics : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsersActionsStatistics object.
        /// </summary>
        /// <param name="iDUserActionStatistic">Initial value of the IDUserActionStatistic property.</param>
        /// <param name="actionType">Initial value of the ActionType property.</param>
        /// <param name="dateAction">Initial value of the DateAction property.</param>
        public static UsersActionsStatistics CreateUsersActionsStatistics(global::System.Guid iDUserActionStatistic, global::System.Int32 actionType, global::System.DateTime dateAction)
        {
            UsersActionsStatistics usersActionsStatistics = new UsersActionsStatistics();
            usersActionsStatistics.IDUserActionStatistic = iDUserActionStatistic;
            usersActionsStatistics.ActionType = actionType;
            usersActionsStatistics.DateAction = dateAction;
            return usersActionsStatistics;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IDUserActionStatistic
        {
            get
            {
                return _IDUserActionStatistic;
            }
            set
            {
                if (_IDUserActionStatistic != value)
                {
                    OnIDUserActionStatisticChanging(value);
                    ReportPropertyChanging("IDUserActionStatistic");
                    _IDUserActionStatistic = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUserActionStatistic");
                    OnIDUserActionStatisticChanged();
                }
            }
        }
        private global::System.Guid _IDUserActionStatistic;
        partial void OnIDUserActionStatisticChanging(global::System.Guid value);
        partial void OnIDUserActionStatisticChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                OnIDUserChanging(value);
                ReportPropertyChanging("IDUser");
                _IDUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUser");
                OnIDUserChanged();
            }
        }
        private Nullable<global::System.Guid> _IDUser;
        partial void OnIDUserChanging(Nullable<global::System.Guid> value);
        partial void OnIDUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> IDRelatedObject
        {
            get
            {
                return _IDRelatedObject;
            }
            set
            {
                OnIDRelatedObjectChanging(value);
                ReportPropertyChanging("IDRelatedObject");
                _IDRelatedObject = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDRelatedObject");
                OnIDRelatedObjectChanged();
            }
        }
        private Nullable<global::System.Guid> _IDRelatedObject;
        partial void OnIDRelatedObjectChanging(Nullable<global::System.Guid> value);
        partial void OnIDRelatedObjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionType
        {
            get
            {
                return _ActionType;
            }
            set
            {
                OnActionTypeChanging(value);
                ReportPropertyChanging("ActionType");
                _ActionType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionType");
                OnActionTypeChanged();
            }
        }
        private global::System.Int32 _ActionType;
        partial void OnActionTypeChanging(global::System.Int32 value);
        partial void OnActionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAction
        {
            get
            {
                return _DateAction;
            }
            set
            {
                OnDateActionChanging(value);
                ReportPropertyChanging("DateAction");
                _DateAction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAction");
                OnDateActionChanged();
            }
        }
        private global::System.DateTime _DateAction;
        partial void OnDateActionChanging(global::System.DateTime value);
        partial void OnDateActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileOrigin
        {
            get
            {
                return _FileOrigin;
            }
            set
            {
                OnFileOriginChanging(value);
                ReportPropertyChanging("FileOrigin");
                _FileOrigin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileOrigin");
                OnFileOriginChanged();
            }
        }
        private global::System.String _FileOrigin;
        partial void OnFileOriginChanging(global::System.String value);
        partial void OnFileOriginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchString
        {
            get
            {
                return _SearchString;
            }
            set
            {
                OnSearchStringChanging(value);
                ReportPropertyChanging("SearchString");
                _SearchString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchString");
                OnSearchStringChanged();
            }
        }
        private global::System.String _SearchString;
        partial void OnSearchStringChanging(global::System.String value);
        partial void OnSearchStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherInfo
        {
            get
            {
                return _OtherInfo;
            }
            set
            {
                OnOtherInfoChanging(value);
                ReportPropertyChanging("OtherInfo");
                _OtherInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherInfo");
                OnOtherInfoChanged();
            }
        }
        private global::System.String _OtherInfo;
        partial void OnOtherInfoChanging(global::System.String value);
        partial void OnOtherInfoChanged();

        #endregion

    
    }

    #endregion

    
}
